# Generated by Django 4.2.7 on 2023-11-22 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Trigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("gap_ignored_bar", "Gap Ignored Bar"),
                            ("powerful_candle", "Powerful Candle"),
                            ("hammer_plus_averages", "Hammer + Averages"),
                            ("open_gap_pb", "Open Gap Pullback"),
                            ("open_gap_pb_averages", "Open Gap Pullback Averages"),
                            ("perfect_pb", "Perfect Pullback"),
                            ("scalp_pb", "Scalp Pullback"),
                            ("stock_open_gap", "Stock Opening Gap"),
                            (
                                "stock_open_gap_breakout",
                                "Stock Opening Gap Breakout Top/Bottom",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
                (
                    "side",
                    models.CharField(
                        choices=[("buy", "Compra"), ("sell", "Venda")], max_length=10
                    ),
                ),
                ("points_result", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "dollars_result",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("error", models.BooleanField()),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="trade_images/"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="notes.asset"
                    ),
                ),
                (
                    "trigger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="notes.trigger"
                    ),
                ),
            ],
        ),
    ]
