# Generated by Django 4.2.7 on 2023-11-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="lot_size",
            field=models.FloatField(default=0.0),
        ),
    ]
